const { createClient } = require('@supabase/supabase-js')
const dotenv = require('dotenv')
dotenv.config({ path: '.env.local' })
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)
supabase.from('opportunities').select('id').eq('company_id', null).limit(1)
  .then(r => console.log('success', r.data, r.error))
  .catch(e => console.log('promise error', e.message))
