import { describe, it, expect } from 'vitest'
import { PDFParse } from 'pdf-parse'
import { renderResumePdf } from '@/lib/resume-optimizer/pdf'
import type { ParsedResume } from '@/types/resume'

const resume: ParsedResume = {
  name: 'Priya Sharma',
  email: 'priya.sharma@example.com',
  phone: '+91-9876543210',
  summary: 'Final-year computer science student focused on backend systems.',
  skills: ['TypeScript', 'PostgreSQL', 'Kubernetes'],
  experience: [
    {
      company: 'Zenith Labs',
      role: 'Backend Engineering Intern',
      start_date: '2025-05',
      end_date: '2025-08',
      location: 'Bengaluru, India',
      bullets: ['Built a rate limiter used by three internal services', 'Reduced query latency by rewriting a hot-path index'],
    },
  ],
  projects: [
    {
      name: 'DistributedCache',
      description: 'An LRU cache with Raft-based replication.',
      technologies: ['Go', 'gRPC'],
    },
  ],
  education: [
    {
      institution: 'IIT Bombay',
      degree: 'B.Tech',
      degree_level: 'bachelors',
      field: 'Computer Science',
      graduation_year: 2026,
      gpa: 8.9,
    },
  ],
}

/**
 * The whole point of the ATS-safe export is that a parser can read it back.
 * A PDF that only looks right on screen (e.g. text rendered as an image)
 * would defeat the feature, so this round-trips the actual generated bytes
 * through a text extractor rather than only checking the buffer is non-empty.
 */
describe('renderResumePdf', () => {
  it('produces a real PDF with an embedded, extractable text layer', async () => {
    const buffer = await renderResumePdf(resume)

    expect(buffer.length).toBeGreaterThan(0)
    expect(buffer.subarray(0, 5).toString('utf-8')).toBe('%PDF-')

    const parser = new PDFParse({ data: buffer })
    const { text } = await parser.getText()
    await parser.destroy()

    expect(text).toContain('Priya Sharma')
    expect(text).toContain('priya.sharma@example.com')
    expect(text).toContain('Zenith Labs')
    expect(text).toContain('Backend Engineering Intern')
    expect(text).toContain('rate limiter used by three internal services')
    expect(text).toContain('DistributedCache')
    expect(text).toContain('IIT Bombay')
    expect(text).toContain('TypeScript')
    expect(text).toContain('Kubernetes')
  })

  it('renders a resume with no optional sections without crashing', async () => {
    const minimal: ParsedResume = { name: 'A. Student', skills: [], experience: [], projects: [], education: [] }
    const buffer = await renderResumePdf(minimal)

    expect(buffer.subarray(0, 5).toString('utf-8')).toBe('%PDF-')

    const parser = new PDFParse({ data: buffer })
    const { text } = await parser.getText()
    await parser.destroy()

    expect(text).toContain('A. Student')
  })

  it('includes certifications and achievements in the downloaded PDF', async () => {
    // Regression test: these two fields were silently dropped from the PDF
    // even when present on the resume — real, verified information the
    // student would never see reflected in the file they actually download.
    const withCredentials: ParsedResume = {
      ...resume,
      certifications: ['AWS Certified Cloud Practitioner (Amazon Web Services)'],
      achievements: ['Top 5 finalist among 120+ teams at a national hackathon'],
    }
    const buffer = await renderResumePdf(withCredentials)

    const parser = new PDFParse({ data: buffer })
    const { text } = await parser.getText()
    await parser.destroy()

    expect(text).toContain('AWS Certified Cloud Practitioner')
    expect(text).toContain('Top 5 finalist among 120+ teams')
  })
})
