-- Validation Data Insert

INSERT INTO public.opportunities (title, company_name, description, apply_url, location, category, status, source, source_id, posted_at, updated_at) VALUES
(
      'Emerge Career (YC S22) Is Hiring a Founding Growth Marketer',
      'Emerge Career',
      'Emerge Career (YC S22) Is Hiring a Founding Growth Marketer',
      'https://www.ycombinator.com/companies/emerge-career/jobs/v0S1AEG-founding-growth-marketer',
      'Remote/Various',
      'Job',
      'Published',
      'ycombinator',
      '48459968',
      NOW(),
      NOW()
    ),
(
      'GoGoGrandparent (YC S16) is hiring Back end Engineers',
      'GoGoGrandparent',
      'GoGoGrandparent (YC S16) is hiring Back end Engineers',
      'https://www.ycombinator.com/companies/gogograndparent/jobs/2vbzAw8-backend-engineer',
      'Remote/Various',
      'Job',
      'Published',
      'ycombinator',
      '48456015',
      NOW(),
      NOW()
    ),
(
      'Proliferate (YC S25) is hiring to building open source Codex',
      'Proliferate',
      'Proliferate (YC S25) is hiring to building open source Codex',
      'https://www.ycombinator.com/companies/proliferate/jobs/L3copvK-founding-engineer',
      'Remote/Various',
      'Job',
      'Published',
      'ycombinator',
      '48436669',
      NOW(),
      NOW()
    ),
(
      '9 Mothers (YC P26) Is Hiring',
      '9 Mothers',
      '9 Mothers (YC P26) Is Hiring',
      'https://9mothers.com/careers',
      'Remote/Various',
      'Job',
      'Published',
      'ycombinator',
      '48433987',
      NOW(),
      NOW()
    ),
(
      'Mbodi AI (YC P25) Is Hiring Founding Machine Learning Engineer (Robotics)',
      'Mbodi AI',
      'Mbodi AI (YC P25) Is Hiring Founding Machine Learning Engineer (Robotics)',
      'https://www.ycombinator.com/companies/mbodi-ai/jobs/WYAcNkX-founding-machine-learning-engineer',
      'Remote/Various',
      'Job',
      'Published',
      'ycombinator',
      '48424103',
      NOW(),
      NOW()
    ),
(
      'Nango (YC W23, dev infra) is hiring staff back end engineers',
      'Nango',
      'Nango (YC W23, dev infra) is hiring staff back end engineers',
      'https://nango.dev/careers',
      'Remote/Various',
      'Job',
      'Published',
      'ycombinator',
      '48411227',
      NOW(),
      NOW()
    ),
(
      'Zettascale (YC S24) Is Hiring Founding FPGA Engineers',
      'Zettascale',
      'Zettascale (YC S24) Is Hiring Founding FPGA Engineers',
      'https://www.ycombinator.com/companies/zettascale/jobs/O9S1vqO-founding-engineer-fpga-rtl-asic-architect',
      'Remote/Various',
      'Job',
      'Published',
      'ycombinator',
      '48401433',
      NOW(),
      NOW()
    ),
(
      'AccessOwl (YC S22) is hiring an AI TypeScript Engineer to connect 300 SaaS tools',
      'AccessOwl',
      'AccessOwl (YC S22) is hiring an AI TypeScript Engineer to connect 300 SaaS tools',
      'https://www.ycombinator.com/companies/accessowl/jobs/hfWAhVp-ai-enabled-senior-software-engineer-typescript-focus',
      'Remote/Various',
      'Job',
      'Published',
      'ycombinator',
      '48397435',
      NOW(),
      NOW()
    ),
(
      'Skyvern (YC S23) Is Hiring Open-Source Loving DevRel Engineers',
      'Skyvern',
      'Skyvern (YC S23) Is Hiring Open-Source Loving DevRel Engineers',
      'https://www.ycombinator.com/companies/skyvern/jobs/1qRTlVx-founding-developer-marketing-open-source-ai',
      'Remote/Various',
      'Job',
      'Published',
      'ycombinator',
      '48386588',
      NOW(),
      NOW()
    ),
(
      'Piramidal (YC W24) – Software Engineers – NYC Onsite',
      'Piramidal',
      'We&#x27;re looking for senior software engineers - frontend, backend, and infra - who are excited about solving difficult problems at the boundary of Foundational AI and Neuroscience. Our core backend and infra stack is Python, Go, and Terraform deployed to various cloud and on-prem, while our frontend stack is React and TypeScript. Bonus points for either: standing up and maintaining reliable streaming systems with a production&#x2F;ops mindset; or building smooth, data-intensive React UIs with modern plotting&#x2F;visualization libraries. You would take an active role in architecture and design, implementation, and hiring from your early days, and will have the opportunity to have ownership commensurate to your capacity and interests.<p>Apply here: <a href="https:&#x2F;&#x2F;job-boards.greenhouse.io&#x2F;piramidalinc" rel="nofollow">https:&#x2F;&#x2F;job-boards.greenhouse.io&#x2F;piramidalinc</a>',
      'https://news.ycombinator.com/item?id=48382853',
      'Remote/Various',
      'Job',
      'Published',
      'ycombinator',
      '48382853',
      NOW(),
      NOW()
    ),
(
      'Great Question (YC W21) Is Hiring Applied AI Interns',
      'Great Question',
      'Great Question (YC W21) Is Hiring Applied AI Interns',
      'https://www.ycombinator.com/companies/great-question/jobs/J5TNvQH-ai-engineer-intern',
      'Remote/Various',
      'Job',
      'Published',
      'ycombinator',
      '48369098',
      NOW(),
      NOW()
    ),
(
      'Telli (YC F24) is hiring in engineering, design, and GTM [Berlin, on-site]',
      'Telli',
      'Telli (YC F24) is hiring in engineering, design, and GTM [Berlin, on-site]',
      'https://hi.telli.com/join-us',
      'Remote/Various',
      'Job',
      'Published',
      'ycombinator',
      '48343635',
      NOW(),
      NOW()
    ),
(
      'Cedana (YC S23) Is Hiring',
      'Cedana',
      'Cedana (YC S23) Is Hiring',
      'https://www.ycombinator.com/companies/cedana/jobs/d1vYocG-forward-deployed-engineer-ai-hpc',
      'Remote/Various',
      'Job',
      'Published',
      'ycombinator',
      '48322030',
      NOW(),
      NOW()
    ),
(
      'RamAIn (YC W26) Is Hiring',
      'RamAIn',
      'RamAIn (YC W26) Is Hiring',
      'https://www.ycombinator.com/companies/ramain/jobs/hqvmyKN-founding-gtm-engineer',
      'Remote/Various',
      'Job',
      'Published',
      'ycombinator',
      '48303599',
      NOW(),
      NOW()
    ),
(
      'Pelica (YC P25) Is Hiring',
      'Pelica',
      'Pelica (YC P25) Is Hiring',
      'https://www.ycombinator.com/companies/pelica/jobs/MDeC49o-machine-learning-engineer',
      'Remote/Various',
      'Job',
      'Published',
      'ycombinator',
      '48301851',
      NOW(),
      NOW()
    );
